apiVersion: v2
name: cert-manager-deployment
description: Deploys cert-manager for TLS certificate management
type: application
version: 0.1.0
appVersion: "1.16.2"

dependencies:
  - name: cert-manager
    version: v1.16.2
    repository: https://charts.jetstack.io
